package com.payegis.cloud.vigil.common.order;

import lombok.Getter;

@Getter
public enum ResultEnum {
    SUCCESS(0, "成功"),
    SYSTEM_ERROR(-400, "系统异常"),
    UNAUTHORIZED(-401, "未授权"),
    AUTH_FAILED(-402, "认证失败"),
    NEED_LOGIN(-403, "未登录"),
    PASSWORDREGULAR_ERROR(-404, "密码至少8个字符，至少1个大写字母，1个小写字母，1个数字和1个特殊字符（范围：!@#$%^&*()_+-=[]{}|'）"),
    //PARAM_ERROR(-404, "参数解析异常"),
    NAME_EXIST(-405, "存在相同的名称"),
    CODE_EXIST(-406, "存在相同的编码"),
    PARAMETER_IS_REFERENCED(-407, "参数被引用"),
    FOREIGN_KEY_WRONG(-408, "外键无法映射"),
    KEY_PARAM_MISSING(-409, "关键参数缺失"),
    //REGULAR_MATCHING_FAILED(-410, "字符正则匹配不正确"),
    PARAM_ERROR(-410,"参数解析异常"),
    JWT_TOKEN_PARSE_FAILED(-411, "token已失效或者解析失败"),
    VERIFY_INFO_FAILED(-412, "信息校验失败"),
    EMAIL_EXIST(-413, "存在相同的邮箱"),
    DOWNLOAD_DATASOURCE_FAILED(-414, "下载自定义数据源模板失败"),
    JWT_TOKEN_MISSING(-415, "token缺失"),
    EXIST_CALLER_USE_SERVICE_CACHE(-416, "存在正在使用该服务缓存的调用方"),
    MOBILE_EXIST(-417, "存在相同的手机号"),
    DATA_TYPE_DIFFERENT(-418, "映射参数数据类型不一致"),
    IVALID_PARSE_STEP(-419, "解析步骤不能选择自身参数"),
    IVALID_CALCULATE_STEP(-420, "组装步骤、计算步骤不能选择自身参数"),
    BLANK_PARSE_STEP(-421, "解析步骤为空"),
    BLANK_CAL_STEP(-422, "计算步骤为空"),
    IVALID_DATA_TYPE(-423, "固定值模式下数据类型不合法"),
    BLANK_JOIN_STEP(-424, "组装步骤为空"),
    ILLEGAL_DATE(-425, "日期不存在或非法"),
    USER_NO_CALLER(-426, "用户没有添加调用方"),
    ILLEGAL_DATE_RANGE(-427, "日期超过范围90天"),
    INVALID_TRANSLATE_VALUE(-428, "转译数据不合法。示例：{\"a\":\"a\",\"b\":\"b\"}"),
    CALLER_NOT_FOUND(-429, "用户未绑定调用方"),
    CODE_INVALID(-430, "编码不合法"),
    PATH_NOT_FOUND(-433, "结果文件未找到"),
    SELECT_UPLOAD_FILE(-434, "请选择上传的文件"),
    UPLOAD_FILE_INVALID(-435, "上传文件格式不正确"),
    LIMIT_FIVE_FILE(-436, "限制上传5个文件"),
    SERVICE_REQUEST_PARAM_IS_EMPTY(-437, "服务请求参数为空"),
    SERVICE_BIND_WITH_DATASOURCE(-438, "禁用数据源前，需要先解除服务-数据源的绑定关系"),
    CALLER_BIND_WITH_SERVICE_IFNO(-439, "禁用服务前，需要先解除调用方-服务的绑定关系"),
    GROUP_BILLING_USE_THIS_PARAM(-440, "组合计费正在使用该参数"),
    DATASOURCE_WARNING_IS_USING_STATUS_CODE(-441, "接口预警正在使用该状态码"),
    DATASOURCE_IS_SERVICE_USING(-442, "接口被服务使用"),
    EVALUATION_IS_USING_COLLECTION(-443, "测试集正在被使用"),
    CONCURRENT_NUM_IS_NULL(-444, "并发用户数为空"),
    CALLER_READD_SERVICE(-445, "重复添加服务"),
    CACHE_KEY_NULL(-446, "缓存key为空"),
    AMOUNT_ERROR(-447, "操作金额有误"),
    REQ_ERROR(-448, "请求数据源失败"),
    USER_URL_EXISTS(-449, "用户已有存在URL"),
    UPDATE_SUCCESS_NOT_CALLBACK(-450, "修改事件状态成功，无回调地址"),
    NOT_FOUND_THIS_APPLICATION(-451, "未找到此事件"),
    NOT_ADMIN(-452, "您不是管理员用户，请联系贵司管理员用户"),
    CANT_CHANGE_CLOSED(-453, "案件已结案"),
    NOT_EXISTS_THIS_TYPE(-454, "该类型不存在"),
    USER_NOT_EXISTS(-455, "用户名或密码错误"),
    QRCODE_LOGIN_FAILED(-456, "扫码登录失败"),
    VERIFY_CODE_FAILURE(-457, "验证码失效"),
    VERIFY_CODE_ERROR(-458, "短信验证码错误或已失效，请重新获取"),
    PASSWORD_DIFF(-459, "输入密码不一致"),

    SLIDER_FAIL(-460, "验证失败，请刷新页面"),
    USER_EXISTS(-461, "用户已存在"),
    USER_NOT_AVAILABLE(-462, "账号不可用，请联系客服"),
    MOBILE_DIFF(-463, "输入手机号与预留手机号不一致"),
    HANDLER_FAILED(-464, "数据处理失败"),
    EMAILSEND_FAILED(-465, "邮件发送异常"),
    ID_MISSING(-466, "主键缺失"),
    CANT_REPORT(-467, "数据准备中"),
    SIGNATURE_CHECK_FAILED(-468, "签名校验失败"),
    PASSWORD_ERROR(-469, "用户名或密码错误"),
    PASSWORD_ENCODE_ERROR(-470, "调用加密算法对密码进行加密时异常"),
    USERNAME_EMPTY_ERROR(-471, "用户名为空"),
    PASSWORD_EMPTY_ERROR(-472, "密码为空"),
    ENTERPRISE_CERTIFICATION_ERROR(-473, "用户未认证"),
    USERNAME_FORMAT_ERROR(-474, "账号格式不正确"),
    CASE_NOT_FIND(-475, "案件不存在"),
    CANT_REPEAT_REQUEST_DATASOURCE(-476, "请不要重复下单"),
    UPDATE_SUCCESS_CALLBACK_FAIL(-477, "回调客户失败"),
    CROP_NAME_TOO_LONG(-478, "公司名称太长了"),
    ID_NOT_FOUND(-479, "主键未找到"),
    DATASOURCE_PARAM_MISSING(-501, "接口基础信息缺失!"),
    DATASOURCE_RESPONSE_PARAM_MISSING(-502, "接口参数返回值信息缺失!"),
    DATASOURCE_STATUS_CODE_MISSING(-503, "接口状态码信息缺失!"),
    DATASOURCE_RESPONSE_PARAM_CAL_STEP_MISSING(-504, "接口参数返回值解析步骤缺失!"),
    DATASOURCE_STATUS_CODE_COUNT_ERROR(-505, "接口状态码定义数量错误!"),
    SERVICE_INFO_PARAM_MISSING(-506, "服务基础信息缺失!"),
    SERVICE_INFO_REQUEST_PARAM_MISSING(-507, "服务参数信息入参值缺失!"),
    SERVICE_INFO_RESPONSE_PARAM_MISSING(-508, "服务参数信息返回值缺失!"),
    DATASOURCE_RESPONSE_PARAM_ANALYSIS_FAILED(-509, "返回值参数自动解析失败!"),
    SERVICE_ROUTE_SUPPLIER_DATASOURCE_MISSING(-510, "路由信息数据接口关联供应商缺失!"),
    DATASOURCE_CUSTOMER_UPLOADJAR_MISSING(-511, "自定义数据接口关联JAR缺失!"),
    SIGN_VERIFY_FAIL(-512, "签名校验失败"),
    OBJECT_ISEMPTY(-513, "实体不存在"),
    FILE_IOERROR(-514, "文件上传/下载失败/取消"),
    ENTER_RESUBMIT(-515, "企业认证信息重复提交"),
    AMOUNT_IS_NULL(-516,"充值金额不能为空"),
    SERVICE_DUE_ERROR(-517,"服务已到期，请续费"),
    PRODUCT_SPECIFICATION_EXIST_ERROR(-518,"已存在其他产品规格，请续费/升级"),
    PRODUCT_SPECIFICATION_TOO_LOW_ERROR(-519,"所选产品规格过低"),
    SERVICE_IS_NULL(-521,"服务不存在"),
    OVER_LIMIT(-522,"超过用户最大服务调用次数"),
    USER_PRODUCT_SPECIFICATION_IS_NULL(-520,"用户未开通对应的产品规格"),
    AGREEMENT_NO_CHECK(-525,"请勾选同意相关协议"),
    ORDER_IS_NOT_YOURS(-590,"非当前用户的订单，无法操作！"),
    ORDER_IS_NOT_EXIST(-523,"订单不存在"),
    IMAGE_IS_NOT_EXIST(-524,"凭证不存在"),
    ORIGIN_PASSWORD_ISEMPTY(-526,"请输入原登录密码，进行密码修改"),
    USER_SPECIFICATION_PAY_ORDER_CANEL_FAIL(-527,"只允许取消交易中的订单"),
    PHONE_FORMAT_ERROR(-528,"手机号格式错误"),
    USER_MEMBER_NOT_EXIST_ERROR(-529,"用户未开通会员"),
    PACKAGE_BAG_NOT_EXIST_ERROR(-530,"套餐包不存在"),
    FEATURE_NOT_SUPPORTED_ERROR(-531,"暂不支持此功能"),
    EKYC_REPORT_OVERDUE(-532,"报告文件已失效"),
    EKYC_COMPANY_NAME_ERROR(-533,"企业名称至少输入4个字符"),
    AMOUNT_NOT_ENOUGH(-534,"余额不足，请充值"),
    BILLING_FAILED(-535,"计费失败"),
    REPORT_ERROR(-536,"eKYC报告处理失败"),
    REPORT_NOMSG(-537,"未查询到相关信息"),

    SEARCH_NO_VIP_OTHER_COUNTRY(-538,"您当前不是会员无法查询国外企业，更多服务请开通会员后使用"),
    SEARCH_NO_VIP_NO_FREE_TIME(-539,"您的%d次国内企业免费通查额度已用完，更多服务请开通会员后使用"),
    SEARCH_NO_ACCESS(-540,"服务未开通"),
    TOO_MANY_PASSWORD_WRONG_TIMES(-541,"密码错误次数过多，请5分钟后再试"),
    PUSH_FAIL(-542,"登录推送失败"),
    USER_CANCELLED(-543,"登陆失败"),
    EKYC_RISK_NOT_FOUND(-544,"未找到风险概览"),
    COMPANY_STATUS_NO_SATISFY(-880,"企业状态不符合"),
    EXIST_CHILD_DEPT(-545, "请移除该组织架构下的所有组织再删除"),
    EXIST_ACCOUNT_DEPT(-546, "请移除该组织架构下的所有账号再删除"),
    SAVE_DEPT_NEED_AUTHENTICATION(-547, "请先完成企业认证"),
    EXIST_ACCOUNT_ROLE(-548, "请移除该角色下的账号后再删除"),
    EXIST_COMPANY_CODE(-549, "统一社会信用代码已认证，请重新输入"),
    NO_PARENT_ACCOUNT(-550, "主账号不能为空"),
    WRONG_PARENT_ACCOUNT(-551, "主账号输入错误，请重新输入"),
    ROLE_NAME_EXIST(-552, "角色已存在，请重新输入"),
    DYNAMIC_TOKEN_ERROR(-553,"请输入正确的动态令牌"),
    COMPANY_CODE_ALREADY_EXISTS(-554,"企业信用代码已经存在"),
    ORDER_NO_SERVICE_EXISTS(-555,"未找到服务信息"),
    NO_PIC_EXISTS(-556,"转账凭证不能为空"),
    SERVICE_SET_EMPTY_ERROR(-557,"服务集为空"),
    ORDER_SERVICE_PACKAGE_EMPTY_ERROR(-558,"规格包不存在"),
    COUPON_CHECK_ERROR(-1004,"当前券无法使用！"),
    COUPON_CHECK_USE_ERROR(-1005,"当前订单已经使用过券，无法叠加使用！"),
    ORDER_NOT_FINISH_ERROR(-559,"订单未完成"),
    REPETITION_RECEIVE_ERROR(-560,"请勿重复领用"),
    NEWS_IMAGE_PARSE_ERROR(-562,"图片解析失败"),
    APP_NOT_EXIST(-563,"应用不存在"),
    DTC_ADDRESS_WRONG(-564,"公钥地址不存在"),
    NO_DTC_RECORD(-565,"DTC记录不存在"),
    DTC_ERROR(-566,"领取失败，请稍后再试"),
    ALREADY_AUTH(-567,"请勿重复认证"),
    ENCRYPT_NULL_ERROR(-568,"请求头encrypt为空"),
    TOO_MANY_COMPANY_AUTH_WRONG(-569,"认证错误次数已达上限"),
    NO_COMPANY_AUTH_PAY(-570,"请确认到账后再提交认证"),
    PRODUCT_SERVICE_NOT_EXIST(-571,"服务信息不存在"),
    USER_CREATE_ERROR(-572,"用户创建失败"),
    COMPANY_NOT_EXIST(-573,"用户创建失败"),
    SECURITY_DOG_ENCRYPT_ERROR(-574,"数据加解密错误"),
    EMPTY_MOBILE_CHECK(-600,"手机号码不能为空"),
    NO_COMPANY_PASS(-575,"请确认审核通过后再提交认证"),
    MINUTE_TOO_MANY_SEND_MSG(-576,"发送频率过快，请稍后再试"),
    TOO_MANY_SEND_MSG(-577,"发送短信次数已达上限，请稍后再试"),
    COMPANY_AUTH_NOT_FINISH(-578,"请先完成一般企业认证"),
    CODE_ERROR (-579,"短信验证码已输错五次，账户已锁定，请十分钟后再试！"),
    SLIDE_VERIFY (-580,"错误三次以上需加入滑动验证"),
    OUT_SYS_ERROR (-581,"外部调用错误"),
    CODE_ACCOUNT_ERROR (-582,"账号密码已输错五次，账户已锁定，请十分钟后再试！"),
    SERVICE_COUNT_NOT_ENOUGH (-583,"剩余额度不足"),
    SEND_SAME_USER (-584,"请选择其他用户"),
    ALREADY_PAY (-585,"请勿重复支付"),
    USERINFO_NOT_EXISTS(-586, "用户不存在"),
    CANCEL_THE_LOGIN(-587, "取消登录"),
    MAINUSER_NOT_EXISTS(-590, "主账号用户不存在");

    private Integer code;
    private String msg;

    ResultEnum(Integer code, String msg) {
        this.code = code;
        this.msg = msg;
    }

}
